### PR TITLE
Update feedstock to version 0.2

### PR DESCRIPTION
**Pull request by dominiquesydow**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests) - **I am using dominiquesydow:update_0_2**
* [x] Bumped the build number (if the version is unchanged) - **version is changed, hence build number stays 0**
* [x] Reset the build number to `0` (if the version changed)  - **version is changed, hence build number is set to 0**
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering) - **I posted comment and magic was done**
* [x] Ensured the license file is being packaged. - **[LICENSE](https://github.com/dominiquesydow/dynophores/blob/v0.2/LICENSE) file part of `dynophore/` repo**

### CODE REVIEW

**Comment by dominiquesydow** [comment]
@conda-forge-admin, please rerender

**Comment by dominiquesydow** [comment]
Hi @jaimergp, could you please check in with me to see if I got the procedure for updating packages right? 

For the future: Do I understand correctly that I am allowed to merge these kinds of PRs without review?

**Comment by jaimergp** [comment]
Yep, LGTM! Feel free to merge, this is your baby :)

**Comment by dominiquesydow** [comment]
Thank you!

**Pull request merged**
